### ISSUE TITLE
FileNotFoundError: No file './data/heli.png' found in working directory

### ISSUE THREAD

**Issue by tmr83** [RelativisticMechanic/PYTHONTROOPER#1]
Traceback (most recent call last):
  File "/home/user/Downloads/PYTHONTROOPER-main/paratrooper.py", line 712, in <module>
    SimpleGraphics.Run(screen_width, screen_height, window_width, window_height, Create, Update, Draw, OnKeyPress, OnKeyPressed, OnKeyRelease, OnMouseMove, OnExit, 'Consolas', 10)
  File "/home/user/Downloads/PYTHONTROOPER-main/SimpleGraphics.py", line 64, in Run
    init()
  File "/home/user/Downloads/PYTHONTROOPER-main/paratrooper.py", line 533, in Create
    heli_image = SimpleGraphics.LoadImage("./data/heli.png")
  File "/home/user/Downloads/PYTHONTROOPER-main/SimpleGraphics.py", line 168, in LoadImage
    return Image(file)
  File "/home/user/Downloads/PYTHONTROOPER-main/SimpleGraphics.py", line 33, in __init__
    self.image_data = pygame.image.load(file)
FileNotFoundError: No file './data/heli.png' found in working directory '/home/user/Downloads/PYTHONTROOPER-main'.

**Comment by RelativisticMechanic** [comment]
Hey uh, sorry for replying this late. I forgot to upload the data files. It should work now.
